Update print_ip.py
trizle@desktop-linux-1-vm:~$ python3 listip.py 
  File "listip.py", line 9
    print '%s' %ip
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('%s' %ip)?